---
title: Архив погоды
author: ''
date: '2019-02-28'
description: Архив погоды
runtime: shiny
output: html_document
---


<iframe height="900px" width="100%" frameborder="no" src="https://francuzribery.shinyapps.io/meteoTable/"> </iframe>

##### Внимание! Время в таблицах - всемирное. Для получения местного времени необходимо прибавить поправку, которая для Красноярского часового пояса равна +7.

#### Пояснения к столбцам:
* Ветер - указаны скорость ветра в м/с - средняя за 10 мин, порывы в срок и между сроками (в фигурных скобках) и направление, откуда дует ветер: С - северный,
СВ - северо-восточный, В - восточный, ЮВ - юго-восточный, Ю - южный, ЮЗ - юго-западный, З - западный, СЗ - северо-западный.
* Видимость - горизонтальная дальность видимости в метрах. При видимости от 1 до 10 км при отсутствии осадков обычно наблюдается дымка, при ухудшении видимости до 1 км и менее - туман. В сухую погоду видимость может ухудшаться дымом, пылью или мглою.
* T - Температура воздуха в цельсиях - температура, измеренная на высоте 2 м над землей.
* Td - Температура точки росы в цельсиях - температура, при понижении до которой содержащийся в воздухе водяной пар достигнет насыщения.
* f - Относительная влажность воздуха в процентах- влажноcть воздуха, измеренная на высоте 2 м над землей.

* P - Атмосферное давление в гигапаскалях - приведенное к уровню моря атмосферное давление.
